tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#0e4b6e",
        "inverse-on-surface": "#eff1f1",
        "on-error": "#ffffff",
        "on-surface": "#191c1d",
        "secondary-fixed-dim": "#a7c8ff",
        "surface-bright": "#f8fafa",
        "tertiary-fixed-dim": "#9bccf6",
        "on-primary-fixed-variant": "#004b73",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d5e3ff",
        "surface-variant": "#e1e3e3",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f4",
        "surface-container-highest": "#e1e3e3",
        "surface-dim": "#d8dada",
        "on-primary": "#ffffff",
        outline: "#707881",
        "secondary-container": "#9fc2fe",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#1f477b",
        "tertiary-fixed": "#cbe6ff",
        "on-secondary": "#ffffff",
        surface: "#f8fafa",
        "surface-container-high": "#e6e8e8",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#3f4850",
        secondary: "#3a5f94",
        "primary-container": "#3498db",
        "on-secondary-container": "#294f83",
        "on-secondary-fixed": "#001b3c",
        "inverse-primary": "#92ccff",
        "on-tertiary-fixed": "#001e30",
        "on-background": "#191c1d",
        "on-primary-fixed": "#001d31",
        "outline-variant": "#bfc7d2",
        tertiary: "#2f6388",
        "inverse-surface": "#2e3131",
        "surface-tint": "#006397",
        "on-tertiary-container": "#002d46",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#cce5ff",
        primary: "#006397",
        "on-primary-container": "#002d47",
        "primary-fixed-dim": "#92ccff",
        "surface-container": "#eceeee",
        background: "#f8fafa",
        "tertiary-container": "#6596bd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-desktop": "32px",
        "stack-md": "24px",
        gutter: "24px",
        base: "8px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "container-padding-mobile": "16px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
};
